# Generated by Django 3.2.3 on 2021-07-11 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210711_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcomment',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.blogpostcomment'),
        ),
    ]
