# Generated by Django 3.2.3 on 2021-07-25 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('disliked_people', models.ManyToManyField(related_name='disliked_comments_carousel', to=settings.AUTH_USER_MODEL)),
                ('liked_people', models.ManyToManyField(related_name='liked_comments_carousel', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_carousel', to='posts.carousel')),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_carousel', to='posts.carouselcomment')),
            ],
        ),
    ]
