# Generated by Django 3.2.3 on 2021-11-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_carouselcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='carousel',
            name='post_points',
            field=models.FloatField(default=0.0),
        ),
    ]
