# Generated by Django 3.2.3 on 2021-11-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20211112_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='digital_signature',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='digital_signature',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
