# Generated by Django 3.2.3 on 2021-11-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20211120_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='digital_signature',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
