# Generated by Django 3.2.3 on 2021-11-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_blogpost_digital_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='digital_signature',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
