# Generated by Django 3.2.3 on 2021-11-21 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20211121_0742'),
        ('posts', '0016_carousel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='group_carousel', to='groups.group'),
        ),
    ]
