# Generated by Django 3.2.3 on 2021-11-12 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_blocks', models.IntegerField(default=0)),
                ('last_block_hash', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_hash', models.TextField(max_length=500, primary_key=True, serialize=False)),
                ('data', models.TextField(max_length=10000)),
                ('prev_block_hash', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mined_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
