# Generated by Django 3.2.3 on 2021-11-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20211112_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='nonce',
            field=models.IntegerField(default=0),
        ),
    ]
