# Generated by Django 3.2.3 on 2021-05-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserProfile", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="user_name",
            new_name="username",
        ),
    ]
