# Generated by Django 3.2.3 on 2021-05-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserProfile", "0002_rename_user_name_customuser_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="username",
            new_name="user_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="email_verified",
        ),
    ]
