# Generated by Django 3.2.3 on 2021-05-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserProfile", "0004_alter_customuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="email verified"),
        ),
    ]
