# Generated by Django 3.2.3 on 2021-05-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserProfile", "0009_auto_20210529_1847"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                default="default_profile_pic.png", upload_to="profile_pictures/"
            ),
        ),
    ]
