# Generated by Django 3.2.3 on 2021-05-30 19:30

import UserProfile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserProfile", "0010_profile_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.CharField(default="", max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="follow_requests_received",
            field=models.ManyToManyField(
                related_name="follow_requests_sent", to="UserProfile.Profile"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                default="default_profile_pic.png",
                upload_to=UserProfile.models.Profile.upload_path,
            ),
        ),
    ]
