# Generated by Django 3.2.3 on 2021-06-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserProfile", "0011_auto_20210530_1930"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(default="", max_length=5000),
        ),
    ]
