# Generated by Django 3.2.3 on 2021-06-22 14:50

import UserProfile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserProfile", "0012_alter_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                null=True, upload_to=UserProfile.models.Profile.upload_path
            ),
        ),
    ]
