# Generated by Django 3.2.3 on 2021-06-23 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("UserProfile", "0013_alter_profile_profile_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailUpdateToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_email", models.EmailField(max_length=250)),
                ("token", models.CharField(max_length=100)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
