# Generated by Django 3.2.3 on 2021-10-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0014_emailupdatetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='private_key',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='profile',
            name='public_key',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='profile',
            name='reward',
            field=models.IntegerField(default=0),
        ),
    ]
