# Generated by Django 3.2.3 on 2021-11-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0016_auto_20211120_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='power',
        ),
        migrations.AddField(
            model_name='profile',
            name='permanent_power',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='temporary_power',
            field=models.FloatField(default=0),
        ),
    ]
