# Generated by Django 3.2.3 on 2021-11-21 02:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0014_alter_blogpost_digital_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_posts', models.ManyToManyField(related_name='group_blog_posts', to='posts.BlogPost')),
                ('carousel_posts', models.ManyToManyField(related_name='group_carousel_posts', to='posts.Carousel')),
                ('election_participants', models.ManyToManyField(related_name='group_election_participants', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='user_groups', to=settings.AUTH_USER_MODEL)),
                ('miners', models.ManyToManyField(related_name='miners_in_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
