# Generated by Django 3.2.3 on 2021-11-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='blog_posts',
        ),
        migrations.RemoveField(
            model_name='group',
            name='carousel_posts',
        ),
    ]
