# Generated by Django 3.2.3 on 2021-11-23 05:50

from django.db import migrations, models
import groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20211121_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='banner',
            field=models.ImageField(default='https://source.unsplash.com/random', upload_to=groups.models.Group.upload_path),
        ),
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.ImageField(default='https://source.unsplash.com/random', upload_to=groups.models.Group.upload_path),
        ),
    ]
