# Generated by Django 3.2.3 on 2021-11-27 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_carousel_group'),
        ('groups', '0004_group_description'),
        ('copyrights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownershipcopyrights',
            name='blogpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.blogpost'),
        ),
        migrations.AddField(
            model_name='ownershipcopyrights',
            name='carousel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.carousel'),
        ),
        migrations.AddField(
            model_name='ownershipcopyrights',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group'),
        ),
    ]
